// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TableItem {
    #[prost(int64, required, tag = "1")]
    pub block_height: i64,
    #[prost(string, required, tag = "2")]
    pub block_timestamp: ::prost::alloc::string::String,
    #[prost(uint64, required, tag = "3")]
    pub tx_version: u64,
    #[prost(string, required, tag = "4")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, optional, tag = "5")]
    pub tx_sequence_number: ::core::option::Option<u64>,
    #[prost(uint64, required, tag = "6")]
    pub change_index: u64,
    #[prost(string, required, tag = "7")]
    pub change_type: ::prost::alloc::string::String,
    #[prost(string, required, tag = "8")]
    pub address: ::prost::alloc::string::String,
    #[prost(string, required, tag = "9")]
    pub state_key_hash: ::prost::alloc::string::String,
    #[prost(message, required, tag = "10")]
    pub key: table_item::Key,
    #[prost(message, optional, tag = "11")]
    pub value: ::core::option::Option<table_item::Value>,
    #[prost(message, required, tag = "12")]
    pub block_unixtimestamp: super::common::UnixTimestamp,
}
/// Nested message and enum types in `TableItem`.
pub mod table_item {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Key {
        #[prost(string, required, tag = "1")]
        pub name: ::prost::alloc::string::String,
        #[prost(string, required, tag = "2")]
        pub r#type: ::prost::alloc::string::String,
    }
    #[derive(serde::Serialize, serde::Deserialize)]
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Value {
        #[prost(string, required, tag = "1")]
        pub content: ::prost::alloc::string::String,
        #[prost(string, required, tag = "2")]
        pub r#type: ::prost::alloc::string::String,
    }
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum TableChangeType {
        DeleteTableItem = 1,
        WriteTableItem = 2,
    }
    impl TableChangeType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                TableChangeType::DeleteTableItem => "delete_table_item",
                TableChangeType::WriteTableItem => "write_table_item",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "delete_table_item" => Some(Self::DeleteTableItem),
                "write_table_item" => Some(Self::WriteTableItem),
                _ => None,
            }
        }
    }
}
