// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Records {
    #[prost(message, repeated, tag = "1")]
    pub blocks: ::prost::alloc::vec::Vec<super::blocks::Block>,
    #[prost(message, repeated, tag = "2")]
    pub transactions: ::prost::alloc::vec::Vec<super::transactions::Transaction>,
    #[prost(message, repeated, tag = "3")]
    pub table_items: ::prost::alloc::vec::Vec<super::table_items::TableItem>,
    #[prost(message, repeated, tag = "4")]
    pub resources: ::prost::alloc::vec::Vec<super::super::json::resources::Resource>,
    #[prost(message, repeated, tag = "5")]
    pub modules: ::prost::alloc::vec::Vec<super::modules::Module>,
    #[prost(message, repeated, tag = "6")]
    pub changes: ::prost::alloc::vec::Vec<super::changes::Change>,
    #[prost(message, repeated, tag = "7")]
    pub events: ::prost::alloc::vec::Vec<super::super::json::events::Event>,
    #[prost(message, repeated, tag = "8")]
    pub signatures: ::prost::alloc::vec::Vec<super::signatures::Signature>,
}
