// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Block {
    #[prost(string, required, tag = "1")]
    pub block_hash: ::prost::alloc::string::String,
    #[prost(string, required, tag = "2")]
    pub block_timestamp: ::prost::alloc::string::String,
    #[prost(int64, required, tag = "3")]
    pub block_height: i64,
    #[prost(uint64, required, tag = "4")]
    pub round: u64,
    #[prost(string, required, tag = "5")]
    pub previous_block_votes_bitvec: ::prost::alloc::string::String,
    #[prost(string, required, tag = "6")]
    pub proposer: ::prost::alloc::string::String,
    #[prost(uint64, required, tag = "7")]
    pub blockmetadata_tx_version: u64,
    #[prost(message, required, tag = "8")]
    pub block_unixtimestamp: super::common::UnixTimestamp,
}
