// This file is @generated by prost-build.
/// TableOptions contain possible output tables.  Each
/// field consists of a boolean and is optional.  If not
/// provided, it should be assumed that it is disabled.
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TableOptions {
    #[prost(bool, optional, tag = "1")]
    pub blocks: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "2")]
    pub transactions: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "3")]
    pub events: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "4")]
    pub changes: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "5")]
    pub modules: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "6")]
    pub table_items: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "7")]
    pub resource: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "8")]
    pub signatures: ::core::option::Option<bool>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IndexingRange {
    #[prost(uint64, tag = "1")]
    pub start: u64,
    #[prost(uint64, tag = "2")]
    pub end: u64,
    /// TableOptions is an optional argument enabling you
    /// to specify which tables should output records.
    ///
    /// If not provided, the assumption is ALL tables
    #[prost(message, optional, tag = "3")]
    pub table: ::core::option::Option<TableOptions>,
}
