// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Event {
    #[prost(int64, required, tag = "1")]
    pub block_height: i64,
    #[prost(string, required, tag = "2")]
    pub block_timestamp: ::prost::alloc::string::String,
    #[prost(uint64, required, tag = "3")]
    pub tx_version: u64,
    #[prost(string, required, tag = "4")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, optional, tag = "5")]
    pub tx_sequence_number: ::core::option::Option<u64>,
    #[prost(uint64, required, tag = "6")]
    pub event_index: u64,
    #[prost(string, required, tag = "7")]
    pub event_type: ::prost::alloc::string::String,
    #[prost(string, required, tag = "8")]
    pub address: ::prost::alloc::string::String,
    #[prost(uint64, required, tag = "9")]
    pub creation_num: u64,
    #[prost(uint64, required, tag = "10")]
    pub sequence_number: u64,
    #[prost(string, required, tag = "11")]
    pub data: ::prost::alloc::string::String,
    #[prost(message, required, tag = "12")]
    pub block_unixtimestamp: super::super::aptos::common::UnixTimestamp,
}
